name: dataherb-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas>=0.23
  - requests>=2.22.0
  - pyyaml>=5.3
  - click==7.0
  - pip
  - pip:
    - fuzzywuzzy>=0.18.0
    - python-Levenshtein>=0.12