name: dataherb-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas>=0.23
  - requests>=2.22.0
  - click==7.0
  - pip
  - pip:
    - rapidfuzz>=0.2.2
    - ruamel.yaml>=0.16.10
    - inquirer>=2.6.3