# mkdocs.yml
site_name: "Dataherb"
site_author: L Ma
site_description: "Dataherb is a dataset management system lives in your terminal"
site_url: "https://dataherb.github.io/dataherb-python"
repo_url: "https://github.com/dataherb/dataherb-python"
edit_uri: "blob/master/docs/"
repo_name: "dataherb/dataherb-python"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon/ms-icon-310x310.png
  logo: assets/logos/logo.png



markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            docstring_style: "restructured-text"
            members: yes
            filters:
              - "^_[^_]"
      watch:
        - dataherb


nav:
  - "Home": index.md
  - "Tutorials":
    - "Tutorials": tutorials/index.md
    - "Configuration": tutorials/configuration/index.md
  - References:
    - "Introduction": references/index.md
    - "dataherb.command": references/command.md
    - "dataherb.flora": "references/flora.md"
    - "dataherb.core":
      - "dataherb.core.base": references/core/base.md
      - "dataherb.core.search": references/core/search.md
    - "dataherb.parse":
      - "dataherb.parse.model_json": references/parse/model_json.md
    - "dataherb.utils":
      - "dataherb.utils.awscli": references/utils/awscli.md
      - "dataherb.utils.data": references/utils/data.md
  - "Changelog": changelog.md

extra_javascript:
  - 'https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js'

