name: Build and Publish Package to Pypi

on:
  push:
    branches:
        - "main"

jobs:
  tests:
    strategy:
      matrix:
        python-version: [3.9, 3.10]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Install from source
        run: pip install .
      - name: Test with pytest
        run: nosetests
  build-n-publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Generate dist
        run: python setup.py sdist
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
